listen_addr = "0.0.0.0:8080"
rpc_addr = "0.0.0.0:3000"
bootstrap_nodes = []
storage_path = "./chain_data"

[genesis]
alice = 1000000
bob = 500000

[validators]
validator_1 = 5000
validator_2 = 3000
validator_3 = 2000
